package fligthsrules.collectstrategies;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CollectObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Tarjeta")
	private java.lang.String tc;
	@org.kie.api.definition.type.Label("Cuotas")
	private java.lang.Integer dues;
	@org.kie.api.definition.type.Label("Codigo de Banco")
	private java.lang.String idBcra;
	@org.kie.api.definition.type.Label("Gateways")
	private java.lang.String strategies;

	@org.kie.api.definition.type.Label(value = "Convenio")
	private java.lang.Boolean UATP;

	public CollectObject() {
	}

	public java.lang.String getTc() {
		return this.tc;
	}

	public void setTc(java.lang.String tc) {
		this.tc = tc;
	}

	public java.lang.Integer getDues() {
		return this.dues;
	}

	public void setDues(java.lang.Integer dues) {
		this.dues = dues;
	}

	public java.lang.String getIdBcra() {
		return this.idBcra;
	}

	public void setIdBcra(java.lang.String idBcra) {
		this.idBcra = idBcra;
	}

	public java.lang.String getStrategies() {
		return this.strategies;
	}

	public void setStrategies(java.lang.String strategies) {
		this.strategies = strategies;
	}

	public java.lang.Boolean getUATP() {
		return this.UATP;
	}

	public void setUATP(java.lang.Boolean UATP) {
		this.UATP = UATP;
	}

	public CollectObject(java.lang.String tc, java.lang.Integer dues,
			java.lang.String idBcra, java.lang.String strategies,
			java.lang.Boolean UATP) {
		this.tc = tc;
		this.dues = dues;
		this.idBcra = idBcra;
		this.strategies = strategies;
		this.UATP = UATP;
	}

}